[project]
name = "bn-tokenizers-embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aber Islam", email = "aber.islam.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
bn-tokenizers-embedding = "bn_tokenizers_embedding:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
